### PR TITLE
(upgrade) Prepare v 1.2.0

### PR DESCRIPTION
**Pull request by aesteve**
* Upgrade Vert.x to 4.4.0
* Upgrade AWS SDK to 2.1109

### CODE REVIEW

**Comment by aesteve** [comment]
Yes for the Localstack tests to run (kind of Integration testing) you have to specifiy [`-Dtests.integration=localstack`](https://github.com/reactiverse/aws-sdk/blob/master/.github/workflows/ci-test.yml#LL26C15-L26C57)

Example in IntelliJ:
Screenshot 2023-03-15 at 08 43 05

**Comment by aesteve** [comment]
Thanks a lot @chris-brace ! It works with the latest Localstack version indeed.

May I ask you to give: [1.2.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/reactiverse/aws-sdk/1.2.0-SNAPSHOT/) a try? If you can?

If it looks good for you I'll be able to publish the release.

**Comment by chris-brace** [comment]
@aesteve its funny, i did these changes locally about 2 days ago and they work but i will pull this branch and run the tests

**Comment by chris-brace** [comment]
tests run with no modification on my m1 when i pull this branch. our integration tests (a very large volume, some of which use AWS testing resources for sqs/s3/kms/sts) appear fine.

**Comment by aesteve** [comment]
Awesome, let's merge this and publish 1.2.0 then!

**Comment by aesteve** [comment]
Sorry I forgot to notify you @chris-brace : 1.2.0 has been released over the weekend: https://central.sonatype.com/artifact/io.reactiverse/aws-sdk/1.1.0/versions

**Pull request merged**
