### PR TITLE
Reuse HttpClient between requests.

### PR DESCRIPTION
**Pull request by zhiguangwang**
io.vertx.core.http.HttpClient is [designed to be reused between requests](https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClient.html).

So we reuse the same HttpClient instance between requests, this:
- Improves performance
- Minimizes memory footprint
- Avoids resource leak (HttpClient pools TCP connections internally)

### CODE REVIEW

**Comment by vietj** [comment]
it seems that the CI does not pass

**Comment by aesteve** [comment]
Merging latest master will make the CI pass.

I checked locally `gradle clean test -Dtests.integration=localstack` and integration tests pass.

**Comment by vietj** [comment]
I'm triggering a new fresh build

**Comment by zhiguangwang** [comment]
@vietj @aesteve I have rebased to latest master then force-pushed this PR, and all CI passed.

**Comment by vietj** [comment]
thanks for the contribution

**Pull request merged**
